------------------------------------상품 테이블-----------------------------
상품번호
회원번호
상품이름
상품메인카테고리
상품서브카테고리
상품가격
상품등록일자
상품상태
조회수
상품설명
상품수량
배송비여부
거래지역
썸네일파일이름
썸네일파일경로
상품거래상태




CREATE TABLE ITEM(
    ITEM_NO             NUMBER          PRIMARY KEY,
    MEMBER_NO           NUMBER,
    ITEM_NAME           VARCHAR2(100)   NOT NULL,
    ITEM_MAIN_CATEGORY  VARCHAR2(100)   NOT NULL,
    ITEM_SUB_CATEGORY   VARCHAR2(100),
    ITEM_PRICE          NUMBER          NOT NULL,
    ITEM_ENROLL_DATE    DATE            DEFAULT SYSDATE,
    ITEM_STATE          VARCHAR2(30)    NOT NULL,
    READCOUNT           NUMBER          DEFAULT 0,
    ITEM_CONTENT        VARCHAR2(1000),
    ITEM_AMOUNT         NUMBER          NOT NULL,
    ITEM_DELIVERY_NY    NUMBER          NOT NULL,
    ITEM_DEAL_REGION    VARCHAR2(50)    NOT NULL,
    ITEM_THUM_FILENAME  VARCHAR2(100),
    ITEM_THUM_FILEPATH  VARCHAR2(100),
    ITEM_DEAL_STATE     VARCHAR2(30)    NOT NULL,
    CONSTRAINT FK_ITEM_MEMBER_NO FOREIGN KEY (MEMBER_NO)REFERENCES 
    MEMBER(MEMBER_NO) ON DELETE SET NULL
);


CREATE SEQUENCE ITEM_NO_SEQ;
DROP TABLE ITEM;
commit;
SELECT * FROM ITEM;


---------------------------------------1:1문의 테이블-----------------------
문의 번호
작성자 회원번호
작성자
문의내용
작성일
파일이름
파일경로
대분류
소분류
답변상태 
답변내용
답변 작성일

create table MTOM_INQUIRY(
MTOM_INQUIRY_NO NUMBER PRIMARY KEY,
MEMBER_NO NUMBER,
MTOM_INQUIRY_WRITER VARCHAR2(40) NOT NULL,
MTOM_INQUIRY_CONTENT VARCHAR2(1000) NOT NULL,
MTOM_INQUIRY_DATE DATE DEFAULT SYSDATE,
FILE_NAME VARCHAR2(100),
FILE_PATH VARCHAR2(100),
MTOM_INQUIRY_MAIN_CATEGORY VARCHAR2(40) NOT NULL,
MTOM_INQUIRY_SUB_CATEGORY VARCHAR2(40) NOT NULL,
MTOM_INQUIRY_ANSWER_STATE NUMBER NOT NULL,
MTOM_INQUIRY_ANSWER_CONTENT VARCHAR2(1000),
MTOM_INQUIRY_ANSWER_DATE DATE DEFAULT SYSDATE,
CONSTRAINT FK_MTOM_INQUIRY_MEMBER_NO FOREIGN KEY (MEMBER_NO) REFERENCES 
MEMBER(MEMBER_NO) ON DELETE CASCADE
);
CREATE SEQUENCE MTOM_INQUIRY_NO_SEQ;

DROP TABLE MTOM_INQUIRY;
SELECT * FROM MTOM_INQUIRY;
COMMIT;


------------------------------- 공지사항 테이블------------------------------
공지사항 번호
제목
내용
작성자
작성일 
조회수
파일이름
파일경로

CREATE TABLE NOTICE(
NOTICE_NO NUMBER PRIMARY KEY,
NOTICE_TITLE VARCHAR2(40) NOT NULL,
NOTICE_CONTENT VARCHAR2(1000) NOT NULL,
NOTICE_WRITER VARCHAR(40) NOT NULL,
NOTICE_DATE DATE DEFAULT SYSDATE,
READCOUNT NUMBER,
FILE_NAME VARCHAR2(100),
FILE_PATH VARCHAR2(100),
CONSTRAINT FK_NOTICE_WRITER FOREIGN KEY (NOTICE_WRITER)REFERENCES 
MEMBER(SHOP_NAME) ON DELETE SET NULL
);

CREATE SEQUENCE NOTICE_NO_SEQ;

DROP TABLE NOTICE;
SELECT * FROM NOTICE;
COMMIT;

-------------------------------회원테이블  = 상점----------------------

회원번호
이메일
비밀번호
이름
가입일자
연락처
집주소
우편번호
계좌
상점이름
상점 소개글
상점 방문수
파일이름
파일 경로


CREATE TABLE MEMBER(
MEMBER_NO NUMBER PRIMARY KEY,
EMAIL VARCHAR2(100) NOT NULL UNIQUE,
MEMBER_PW VARCHAR2(40) NOT NULL,
MEMBER_NAME VARCHAR2(40) NOT NULL,
ENROLL_DATE DATE DEFAULT SYSDATE,
PHONE VARCHAR2(40) NOT NULL,
ADDRESS VARCHAR2(100) NOT NULL,
ZIP_CODE VARCHAR2(50) NOT NULL,
MEMBER_BANK VARCHAR2(50),
MEMBER_ACCOUNT VARCHAR2(50),
SHOP_NAME VARCHAR2(40) UNIQUE,
SHOP_CONTENT VARCHAR2(500),
SHOP_READCOUNT NUMBER DEFAULT 0,
FILE_NAME VARCHAR2(100),
FILE_PATH VARCHAR2(100)
);

CREATE SEQUENCE MEMBER_NO_SEQ;

DROP TABLE MEMBER;
SELECT * FROM MEMBER;
COMMIT;
------------------------------ 알림 테이블 -----------------------------
알림번호 
판매자 회원번호
구매자 상점이름
알림종류
상품명
댓글내용
후기내용 
알림 등록 시간

CREATE TABLE ALARM(
ALARM_NO NUMBER PRIMARY KEY,
ALARM_SELLER_NO NUMBER,
ALARM_BUYER_SHOP_NAME VARCHAR2(40),
ALARM_TYPE VARCHAR2(100) NOT NULL,
ALARM_ITEM_NAME VARCHAR2(100),
ALARM_ITEM_INQUIRY_COMMENT VARCHAR2(1000),
ALARM_MEMBER_REVIEW_COMMENT VARCHAR2(500),
ALARM_DATE DATE DEFAULT SYSDATE,
CONSTRAINT FK_ARARM_SELLER_NO FOREIGN KEY (ALARM_SELLER_NO)REFERENCES 
MEMBER(MEMBER_NO) ON DELETE SET NULL,
CONSTRAINT FK_ARARM_BUYER_SHOP_NAME FOREIGN KEY (ALARM_BUYER_SHOP_NAME)REFERENCES 
MEMBER(SHOP_NAME) ON DELETE SET NULL
);

CREATE SEQUENCE ALARM_NO_SEQ;
DROP TABLE ALARM;
SELECT * FROM ALARM;
COMMIT;

------------------------------- 찜 테이블 -------------------------------
찜 
상점번호(상품을 찜한 상점)
상품번호

CREATE TABLE FAVORITE(
SHOP_NO NUMBER NOT NULL,
ITEM_NO NUMBER NOT NULL,
CONSTRAINT FK_SHOP_NO FOREIGN KEY (SHOP_NO)REFERENCES 
MEMBER(MEMBER_NO) ON DELETE CASCADE,
CONSTRAINT FK_ITEM_NO FOREIGN KEY (ITEM_NO)REFERENCES
ITEM(ITEM_NO) ON DELETE CASCADE
);

DROP TABLE FAVORITE;
SELECT * FROM FAVORITE;
COMMIT;

-------------------------------검색어 테이블 ------------------------------
검색내용
검색일자
검색 회수

CREATE TABLE SEARCH(
SEARCH_CONTENT VARCHAR2(100) PRIMARY KEY,
SEARCH_DATE DATE DEFAULT SYSDATE,
SEARCH_COUNT NUMBER
);

DROP TABLE SEARCH;
SELECT * FROM SEARCH;
COMMIT;
------------------------------선호하는 지역(3군대) 테이블-------------------
회원번호
주소선택

CREATE TABLE MEMBER_ADDRES(
MEMBER_NO NUMBER,
ADDR_CHOICE VARCHAR2(100),
CONSTRAINT FK_MEMBER_ADDRS_MEMBER_NO FOREIGN KEY (MEMBER_NO)REFERENCES 
MEMBER(MEMBER_NO) ON DELETE CASCADE
);

DROP TABLE MEMBER_ADDRES;
SELECT * FROM MEMBER_ADDRES;
COMMIT;
-----------------------------상점 후기 테이블 ---------------------------------

후기번호
상점번호
작성자 상점 이름
후기 작성일
후기내용
별점

CREATE TABLE REVIEW(
REVIEW_NO NUMBER PRIMARY KEY,
SHOP_NO NUMBER,
REVIEW_WRITER VARCHAR2(40),
REVIEW_DATE DATE DEFAULT SYSDATE,
REVIEW_CONTENT VARCHAR2(500) NOT NULL,
REVIEW_SCORE NUMBER,
CONSTRAINT FK_REVIEW_SHOP_NO FOREIGN KEY (SHOP_NO)REFERENCES 
MEMBER(MEMBER_NO) ON DELETE CASCADE,
CONSTRAINT FK_REVIEW_WRITER FOREIGN KEY (REVIEW_WRITER)REFERENCES 
MEMBER(SHOP_NAME) ON DELETE SET NULL
);

CREATE SEQUENCE REVIEW_NO_SEQ;

DROP TABLE REVIEW;
SELECT * FROM REVIEW;
COMMIT;
-------------------------------  결제 테이블---------------------------------
상품번호
회원번호
관리자 고유ID
결제금액 
결제 상태
결제일
카드 승인번호
결제 수수료
상점 거래ID
환불 여부

CREATE TABLE PAYMENT(
MERCHANT_UID VARCHAR2(40) PRIMARY KEY,
ITEM_NO NUMBER,
MEMBER_NO NUMBER,
IMP_UID VARCHAR2(40) ,
PAYMENT_PAY NUMBER NOT NULL,
PAYMENT_STATE VARCHAR2(40) NOT NULL,
PAYMENT_DATE DATE DEFAULT SYSDATE,
PAYMENT_APPLY_NUM VARCHAR2(40) NOT NULL,
PAYMENT_COMMISSION NUMBER,
PAYMENT_NY VARCHAR2(40) NOT NULL DEFAULT N,
CONSTRAINT FK_PAYMENT_ITEM_NO FOREIGN KEY (ITEM_NO)REFERENCES 
ITEM(ITEM_NO) ON DELETE SET NULL,
CONSTRAINT FK_PAYMENT_MEMBER_NO FOREIGN KEY (MEMBER_NO)REFERENCES 
MEMBER(MEMBER_NO) ON DELETE SET NULL
);

DROP TABLE PAYMENT;
SELECT * FROM PAYMENT;
COMMIT;

-------------------------- 거래 테이블 ----------------------------------------
거래 번호 
구매자
판매자
상품번호
거래상태

CREATE TABLE DEAL(
DEAL_NO NUMBER PRIMARY KEY ,
BUYER NUMBER ,
SALER NUMBER ,
ITEM_NO NUMBER ,
DEAL_STATE VARCHAR2(20),
DEAL_END_DATE DATE,
CONSTRAINT FK_BUYER FOREIGN KEY (BUYER)REFERENCES 
MEMBER(MEMBER_NO) ON DELETE SET NULL,
CONSTRAINT FK_SALER FOREIGN KEY (SALER)REFERENCES 
MEMBER(MEMBER_NO) ON DELETE SET NULL,
CONSTRAINT FK_DEAL_ITEM_NO FOREIGN KEY (ITEM_NO)REFERENCES 
ITEM(ITEM_NO) ON DELETE SET NULL
);

CREATE SEQUENCE DEAL_NO_SEQ;
DROP TABLE DEAL;
SELECT * FROM DEAL;
COMMIT;

------------------------------ 상품 문의 테이블 --------------------------
댓글 번호
작성자 닉네임
댓글달린 상품번호
댓글 내용
댓글 작성일
댓글 단계
답글달린 댓글번호

CREATE TABLE ITEM_INQUIRY(
ITEM_INQUIRY_NO NUMBER PRIMARY KEY,
ITEM_INQUIRY_WRITER VARCHAR2(40),
ITEM_REF NUMBER,
ITEM_INQUIRY_COMMENT VARCHAR2(1000) NOT NULL,
ITEM_INQUIRY_DATE DATE DEFAULT SYSDATE,
ITEM_INQUIRY_LEVEL NUMBER NOT NULL,
ITEM_INQUIRY_REF NUMBER ,
CONSTRAINT FK_ITEM_INQUIRY_NO FOREIGN KEY (ITEM_INQUIRY_NO)REFERENCES 
ITEM(ITEM_NO) ON DELETE SET NULL,
CONSTRAINT FK_ITEM_INQUIRY_REF FOREIGN KEY (ITEM_INQUIRY_REF)REFERENCES 
ITEM_INQUIRY(ITEM_INQUIRY_NO) ON DELETE SET NULL
);

CREATE SEQUENCE ITEM_INQUIRY_NO_SEQ;

DROP TABLE ITEM_INQUIRY;
SELECT * FROM ITEM_INQUIRY;
COMMIT;


------------------------------상품 이미지 테이블-------------------------
상품 번호
파일이름
파일 경로
썸네일 설정 여부

CREATE TABLE ITEM_IMAGE(
ITEM_NO NUMBER NOT NULL,
FILE_NAME VARCHAR2(100) NOT NULL,
FILE_PATH VARCHAR2(100) NOT NULL,
THUM_NY NUMBER NOT NULL,
CONSTRAINT FK_ITEM_IMAGE_ITEM_NO FOREIGN KEY (ITEM_NO)REFERENCES 
ITEM(ITEM_NO) ON DELETE SET NULL
);

DROP TABLE ITEM_IMAGE;
SELECT * FROM ITEM_IMAGE;
COMMIT;










